### Create user
POST http://localhost:8080/user
Content-Type: application/json

{
  "nombre": "Sebastian",
  "apellido_paterno": "Marines",
  "apellido_materno": "Alvarez",
  "email": "test@gmail.com",
  "password": "hola"
}

### Login
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "hola"
}
